### PR TITLE
Feature/logstash json encoder

### PR DESCRIPTION
**Pull request by sergiojoker11**
This is as far as I got. For some reason, I introduced regression because logback would not even start even though the encoder is commented out.
The error I am experiencing is: 
```
Failed to instantiate SLF4J LoggerFactory
engine      | Reported exception:
engine      | java.lang.NoClassDefFoundError: org/apache/juli/logging/ch/qos/logback/core/joran/spi/JoranException
engine      | 	at org.apache.juli.logging.org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
engine      | 	at org.apache.juli.logging.org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
engine      | 	at org.apache.juli.logging.org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
engine      | 	at org.apache.juli.logging.org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
engine      | 	at org.apache.juli.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
engine      | 	at org.apache.juli.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
engine      | 	at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:273)
engine      | 	at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:51)
engine      | Caused by: java.lang.ClassNotFoundException: org.apache.juli.logging.ch.qos.logback.core.joran.spi.JoranException
engine      | 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
engine      | 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
engine      | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
engine      | 	... 8 more
engine      | Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/juli/logging/ch/qos/logback/core/joran/spi/JoranException
engine      | 	at org.apache.juli.logging.org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
engine      | 	at org.apache.juli.logging.org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
engine      | 	at org.apache.juli.logging.org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
engine      | 	at org.apache.juli.logging.org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
engine      | 	at org.apache.juli.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
engine      | 	at org.apache.juli.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
engine      | 	at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:273)
engine      | 	at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:51)
engine      | Caused by: java.lang.ClassNotFoundException: org.apache.juli.logging.ch.qos.logback.core.joran.spi.JoranException
engine      | 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
engine      | 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
engine      | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

```
The reproduction steps are:
 - I set the configuration value with the path to the logback.xml.
 `export JAVA_OPTS="$JAVA_OPTS -Djuli-logback.configurationFile=file:/camunda/conf/logback/logback.xml"`
 - Having this logback.xml:
 ```
 <configuration>
  <appender name="console" class="org.apache.juli.logging.ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%date{ISO8601} [%thread] %-5level %logger{15} - %msg %n</pattern>
      <charset>UTF-8</charset>
    </encoder>
  </appender>

  <!-- <appender name="json" class="org.apache.juli.logging.ch.qos.logback.core.ConsoleAppender">
    <encoder class="org.apache.juli.logging.net.logstash.logback.encoder.LogstashEncoder">
      <timestampPattern>yyyy-MM-dd'T'HH:mm:ss.SSS</timestampPattern>
      <fieldNames>
        <timestamp>timestamp</timestamp>
        <level>severity</level>
      </fieldNames>
      <charset>UTF-8</charset>
    </encoder>
  </appender> -->


<logger name="org.apache.catalina" level="info" />
<logger name="org.apache.tomcat" level="info" />

  <root level="info">
    <!-- <appender-ref ref="STDOUT" /> -->
    <appender-ref ref="${LOGBACK_APPENDER:-json}" />
  </root>

</configuration>
 ```
 - Remove /{CATALINA_HOME}/conf/logging.properties
 - Replace  /{CATALINA_HOME}/bin/tomcat-juli.jar with the resulting package of the mvn project.
 - Start up tomcat.
 
 Note: FYI, CATALINA_HOME == CATALINA_BASE.

### CODE REVIEW

**Comment by hazendaz** [comment]
seemed to work for me in my default setup but it does cause the resulting jar to grow considerably in size.  Might make more sense to maybe have a separate deliverable to include that bit.  Is jackson necessary for that module?  What I would suggest is taking barebones 'master' build of this and making sure you have it setup as needed.  Then try making the adjustment.  My guess is that you don't have the entire binary when you tested it.  Possibly due to IDE trying to build when copied potentially.  Anyway, all I didwas apply the same pom changes but made the new items all optional as that keeps the usage of the final jar clean from pulling back in the originals.  resulting jar is 3.5mb and simple startup (I didn't change anything in my case) just worked.  I did notice here in your file you have parts of the new appender still configured.  Not sure other than that...

**Comment by adeo20007757** [comment]
Hi,
In the pom.xml file, you deleted the line `<include>ch.qos.logback:logback-core</include>` in the artifactSet tag in the configuration of the maven-shade-plugin when you added `<include>com.fasterxml.jackson.core:jackson-core</include>`.
If you restore it, it must work.

**Comment by hazendaz** [comment]
brought up to date but may not continue with this, logback now has native encoder support, see https://jira.qos.ch/browse/LOGBACK-1734.  We are looking at this off similar PR on the tomcat 9 line, determining outcome we will address on other tomcat lines.

**Comment by hazendaz** [comment]
Taking as-is, will sync up any differences or adjustments before release as older PRs also out there for same item on older tomcats.  Will ensure all sync'd before I release so we have basically same stuff.

**Pull request merged**
